export const escape = (v='') => String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cats=['随想','文章','收藏','作品'];
const date=v=>new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'long',day:'numeric',timeZone:'Asia/Shanghai'}).format(new Date(v));
const query=(type,tag)=>'/notes/?'+new URLSearchParams({...type?{type}:{},...tag?{tag}:{}});
const tags=(r)=>`<div class="entry-tags">${r.tags.map(t=>`<a href="${escape(query(null,t))}"># ${escape(t)}</a>`).join('')}</div>`;
function nav(name){const links=[['全部记录','/notes/'],...cats.map(t=>[t,query(t)])].map(([label,href])=>`<a href="${escape(href)}"><span>${escape(label)}</span></a>`).join('');return `<header class="journal-header"><a class="journal-logo" href="/">${escape(name)}</a><nav class="desktop-journal-nav" aria-label="主导航">${links}</nav><details class="mobile-journal-nav"><summary class="mobile-menu-trigger">Menu</summary><nav class="mobile-links" aria-label="移动导航">${links}</nav></details></header>`;}
function layout(title,body,description=''){return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)}</title><meta name="description" content="${escape(description)}"><link rel="stylesheet" href="/assets/style.css"></head><body>${body}</body></html>`;}
export function home(site){const lines=site.bio.split(/(?<=[。！？\n])/).filter(x=>x.trim());return layout(site.name,`<div class="journal journal-home">${nav(site.name)}<main class="early-home"><div class="early-composition"><div class="early-gray-band" aria-hidden="true"></div><img class="early-image" src="/assets/home-image.png" alt="自然光下的房间与两把座椅" width="736" height="915"><section class="early-quote" aria-label="个人介绍"><h1 class="sr-only">${escape(site.name)}</h1><p>${lines.map((x,i)=>`<span class="quote-line"><span>${i===0?'“':''}${escape(x)}${i===lines.length-1?'”':''}</span></span>`).join('')}</p></section></div><div class="early-bottom" aria-hidden="true"></div></main></div>`,site.bio);}
export function listing(site,entries){return layout('全部记录 · '+site.name,`<div class="journal">${nav(site.name)}<main class="journal-main"><section class="journal-intro"><h1 id="list-heading">全部记录</h1><p class="eyebrow" id="list-index">[ALL NOTES]</p></section><nav class="journal-nav" aria-label="内容分类">${['全部',...cats].map(t=>`<a data-category="${escape(t)}" href="${escape(query(t==='全部'?null:t))}">${t}</a>`).join('')}</nav><div id="tag-filter" class="tag-filter" hidden></div><div class="journal-list">${entries.map((r,i)=>`<article class="journal-entry" data-type="${escape(r.type)}" data-tags="${escape(JSON.stringify(r.tags))}"><span class="entry-number">[ ${String(i+1).padStart(2,'0')} ]</span><div class="entry-content"><a class="entry-title" href="/notes/${escape(r.id)}/">${escape(r.title)}<span class="arrow">↗</span></a><div class="entry-meta"><time>${escape(date(r.date))}</time><span>· ${escape(r.type)}</span></div>${r.summary?`<p>${escape(r.summary)}</p>`:''}${tags(r)}</div></article>`).join('')}<div class="journal-empty" id="empty" ${entries.length?'hidden':''}><span class="empty-index">[ 00 ]</span><h2>这里还没有这样的记录</h2><p>写下的想法，会慢慢在这里相遇。</p></div></div></main><footer class="journal-footer"><span>${escape(site.name)}</span><span>Made with curiosity.</span></footer></div><script src="/assets/filter.js" defer></script>`,site.bio);}
function rich(items){return items.map(r=>{let t=escape(r.text);if(r.code)t=`<code>${t}</code>`;if(r.bold)t=`<strong>${t}</strong>`;if(r.italic)t=`<em>${t}</em>`;if(r.strike)t=`<s>${t}</s>`;return /^https?:\/\//i.test(r.url||'')?`<a href="${escape(r.url)}" target="_blank" rel="noreferrer">${t}</a>`:t;}).join('');}
export function blocksHtml(blocks){let html='';for(let i=0;i<blocks.length;i++){const b=blocks[i];const text=rich(b.rich),nested=blocksHtml(b.children||[]);if(['bulleted_list_item','numbered_list_item'].includes(b.type)){const tag=b.type==='numbered_list_item'?'ol':'ul';let items=`<li>${text}${nested}</li>`;while(blocks[i+1]?.type===b.type){const n=blocks[++i];items+=`<li>${rich(n.rich)}${blocksHtml(n.children||[])}</li>`;}html+=`<${tag}>${items}</${tag}>`;continue;}if(b.type.startsWith('heading_')){const level=Math.min(Number(b.type.at(-1))+1,4);html+=`<h${level}>${text}</h${level}>${nested}`;}else if(b.type==='divider')html+='<hr>';else if(b.type==='code')html+=`<pre><code>${escape(b.rich.map(r=>r.text).join(''))}</code></pre>`;else if(b.type==='quote'||b.type==='callout')html+=`<blockquote>${text}${nested}</blockquote>`;else if(b.type==='toggle')html+=`<details><summary>${text}</summary>${nested}</details>`;else if(b.type==='column'||b.type==='column_list')html+=nested;else html+=`<p>${b.type==='to_do'?(b.checked?'☑ ':'☐ '):''}${text}</p>${nested}`;}return html;}
export function article(site,r){return layout(r.title+' · '+site.name,`<main class="article-page"><a class="back-link" href="/notes/">← 返回记录</a><div class="article-meta">${escape(r.type)} · ${escape(date(r.date))}</div><h1>${escape(r.title)}</h1>${tags(r)}<div class="article-body">${blocksHtml(r.blocks)}</div></main>`,r.summary);}
export function missing(site){return layout('页面不存在 · '+site.name,`<main class="article-page"><h1>这条记录暂时不在这里。</h1><p>内容可能已经撤回，或链接有误。</p><a href="/notes/">查看全部记录 →</a></main>`);}
